# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('object_id',
                 models.PositiveIntegerField(
                     null=True)),
                ('data',
                 models.FileField(
                     upload_to='')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('content_type',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='contenttypes.ContentType')),
            ],
        ),
    ]
