# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20171004_1832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='attachments',
        ),
    ]
