# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attachments', '0003_auto_20171005_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'attachment_images',
            },
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
