# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('description',
                 models.TextField()),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('object_id',
                 models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='contenttypes.ContentType')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
