# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedbacks',
        ),
    ]
