# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_auto_20171005_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'In progress'), (2, 'Done')], db_index=True, default=0),
        ),
    ]
