# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_specialties'),
        ('feedbacks', '0003_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
            preserve_default=False,
        ),
    ]
