# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.DecimalField(
                decimal_places=0,
                default=100000,
                max_digits=8),
            preserve_default=False,
        ),
    ]
