# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='resumes.Resume'),
        ),
    ]
