# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_auto_20180121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='start_date',
            field=models.DateField(),
        ),
    ]
