# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 12:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='social_networks',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
