# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_auto_20180201_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
