# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
            options={
                'db_table': 'interview_employees',
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewees',
            field=models.ManyToManyField(related_name='interviewees', through='interviews.InterviewEmployee', to=settings.AUTH_USER_MODEL),
        ),
    ]
