# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20170830_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='passed',
            field=models.NullBooleanField(),
        ),
    ]
