# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20170902_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewemployee',
            name='role',
        ),
    ]
