# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20170902_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='assigned_at',
            field=models.DateTimeField(),
        ),
    ]
