# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20170824_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='name',
            new_name='title',
        ),
    ]
