# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('vacancies', '0003_auto_20170824_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy')),
            ],
            options={
                'db_table': 'vacancy_skills',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(through='vacancies.VacancySkill', to='skills.Skill'),
        ),
    ]
