# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20170826_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='vacancyskill',
            name='vacancy',
        ),
        # migrations.AlterField(
        #     model_name='vacancy',
        #     name='skills',
        #     field=models.ManyToManyField(to='skills.Skill'),
        # ),
        migrations.DeleteModel(
            name='VacancySkill',
        ),
    ]
