# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_remove_skill_vacancies'),
        ('vacancies', '0006_remove_vacancy_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
    ]
