# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_vacancy_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
