# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_companymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(
                through='companies.CompanyMember',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='companymember',
            table='company_members',
        ),
    ]
