# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_auto_20170821_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together=set([('user', 'company')]),
        ),
        migrations.AlterIndexTogether(
            name='companymember',
            index_together=set([('user', 'company')]),
        ),
    ]
