# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170821_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
