# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20170903_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
