# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.IntegerField(
                choices=[
                    (1,
                     'Company Owner'),
                    (2,
                     'HR'),
                    (3,
                     'Candidate'),
                    (4,
                     'Employee')],
                db_index=True,
                default=4),
        ),
    ]
