# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180309_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
