# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='parent',
        ),
    ]
