# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20170826_2204'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='vacancies',
            field=models.ManyToManyField(through='vacancies.VacancySkill', to='vacancies.Vacancy'),
        ),
    ]
