# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_vacancies'),
    ]

    operations = [
    ]
