# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20170819_0924'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(through='companies.CompanyMember', to='companies.Company'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
