# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20170830_1516'),
        ('authorization', '0002_auto_20170819_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interviews',
            field=models.ManyToManyField(
                through='interviews.InterviewEmployee',
                to='interviews.Interview'),
        ),
    ]
