from rest_framework import serializers
from interviews.models import Interview, InterviewEmployee
from .interview_employee_serializer import InterviewEmployeeSerializer

from .interview_serializer import InterviewSerializer
