from rest_framework import serializers
from interviews.models import Interview, InterviewEmployee
from .interview_employee_serializer import InterviewEmployeeSerializer


from .base_interview_serializer import BaseInterviewSerializer
from .interview_serializer import InterviewSerializer
